import { Brand, Agency, Plan, Subscription, AuditLog, User } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'john@example.com',
    name: 'John Admin',
    role: 'admin',
    createdAt: new Date('2024-01-15'),
    lastLogin: new Date('2024-04-19'),
  },
  {
    id: '2',
    email: 'sarah@example.com',
    name: 'Sarah Moderator',
    role: 'moderator',
    createdAt: new Date('2024-02-01'),
    lastLogin: new Date('2024-04-18'),
  },
];

export const mockBrands: Brand[] = [
  {
    id: 'brand-1',
    name: 'TechFlow Solutions',
    website: 'techflow.io',
    ownerEmail: 'owner1@techflow.io',
    plan: 'professional',
    status: 'active',
    visibility: 'public',
    seatsUsed: 8,
    seatsLimit: 10,
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'brand-2',
    name: 'Creative Minds Studio',
    website: 'creativeminds.co',
    ownerEmail: 'contact@creativeminds.co',
    plan: 'starter',
    status: 'active',
    visibility: 'private',
    seatsUsed: 3,
    seatsLimit: 5,
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'brand-3',
    name: 'Enterprise Dynamics',
    website: 'enterprise-dynamics.com',
    ownerEmail: 'admin@enterprise-dynamics.com',
    plan: 'enterprise',
    status: 'active',
    visibility: 'public',
    seatsUsed: 45,
    seatsLimit: 100,
    createdAt: new Date('2023-06-20'),
  },
  {
    id: 'brand-4',
    name: 'StartupHub',
    website: 'startuphub.dev',
    ownerEmail: 'team@startuphub.dev',
    plan: 'starter',
    status: 'suspended',
    visibility: 'private',
    seatsUsed: 2,
    seatsLimit: 5,
    createdAt: new Date('2024-03-05'),
  },
];

export const mockAgencies: Agency[] = [
  {
    id: 'agency-1',
    name: 'Digital Marketing Pro',
    description: 'Full-service digital marketing agency',
    website: 'digitalmarketingpro.com',
    ownerEmail: 'ceo@digitalmarketingpro.com',
    status: 'active',
    brandCount: 5,
    totalSeatsUsed: 24,
    createdAt: new Date('2023-05-10'),
    brands: [
      {
        id: 'agency-1-brand-1',
        name: 'Agency Brand A',
        website: 'agency-brand-a.com',
        ownerEmail: 'owner@agency-brand-a.com',
        plan: 'professional',
        status: 'active',
        visibility: 'public',
        agencyId: 'agency-1',
        seatsUsed: 5,
        seatsLimit: 10,
        createdAt: new Date('2023-06-15'),
      },
      {
        id: 'agency-1-brand-2',
        name: 'Agency Brand B',
        website: 'agency-brand-b.com',
        ownerEmail: 'owner@agency-brand-b.com',
        plan: 'starter',
        status: 'active',
        visibility: 'private',
        agencyId: 'agency-1',
        seatsUsed: 3,
        seatsLimit: 5,
        createdAt: new Date('2023-07-20'),
      },
    ],
  },
  {
    id: 'agency-2',
    name: 'Growth Accelerators',
    description: 'Growth marketing specialists',
    website: 'growthaccelerators.io',
    ownerEmail: 'hello@growthaccelerators.io',
    status: 'active',
    brandCount: 3,
    totalSeatsUsed: 12,
    createdAt: new Date('2023-08-01'),
    brands: [],
  },
];

export const mockPlans: Plan[] = [
  {
    id: 'plan-1',
    name: 'starter',
    monthlyPrice: 29,
    yearlyPrice: 290,
    features: ['Up to 3 brands', '5 team members', 'Basic analytics', 'Email support'],
    status: 'available',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'plan-2',
    name: 'professional',
    monthlyPrice: 99,
    yearlyPrice: 990,
    features: ['Up to 10 brands', 'Unlimited team members', 'Advanced analytics', 'Priority support', 'Custom integrations'],
    status: 'available',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'plan-3',
    name: 'enterprise',
    monthlyPrice: 299,
    yearlyPrice: 2990,
    features: ['Unlimited brands', 'Unlimited team members', 'Real-time analytics', 'Dedicated support', 'API access'],
    status: 'available',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-02-15'),
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub-1',
    organizationId: 'brand-1',
    organizationType: 'brand',
    organizationName: 'TechFlow Solutions',
    currentPlan: 'professional',
    billingStatus: 'active',
    seatsUsed: 8,
    seatsLimit: 10,
    billingCycle: 'yearly',
    renewalDate: new Date('2025-01-10'),
    status: 'active',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'sub-2',
    organizationId: 'brand-2',
    organizationType: 'brand',
    organizationName: 'Creative Minds Studio',
    currentPlan: 'starter',
    billingStatus: 'active',
    seatsUsed: 3,
    seatsLimit: 5,
    billingCycle: 'monthly',
    renewalDate: new Date('2024-05-15'),
    status: 'active',
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'sub-3',
    organizationId: 'brand-3',
    organizationType: 'brand',
    organizationName: 'Enterprise Dynamics',
    currentPlan: 'enterprise',
    billingStatus: 'active',
    seatsUsed: 45,
    seatsLimit: 100,
    billingCycle: 'yearly',
    renewalDate: new Date('2025-06-20'),
    status: 'active',
    createdAt: new Date('2023-06-20'),
  },
  {
    id: 'sub-4',
    organizationId: 'brand-4',
    organizationType: 'brand',
    organizationName: 'StartupHub',
    currentPlan: 'starter',
    billingStatus: 'past_due',
    seatsUsed: 2,
    seatsLimit: 5,
    billingCycle: 'monthly',
    renewalDate: new Date('2024-03-05'),
    status: 'suspended',
    createdAt: new Date('2024-03-05'),
  },
];

export const mockLogs: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: new Date('2024-04-19T14:32:00Z'),
    actor: 'john@example.com',
    action: 'login',
    module: 'auth',
    targetEntity: 'User',
    targetId: 'user-1',
    status: 'success',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    details: { method: 'email_password' },
  },
  {
    id: 'log-2',
    timestamp: new Date('2024-04-19T10:15:00Z'),
    actor: 'sarah@example.com',
    action: 'update',
    module: 'organizations',
    targetEntity: 'Brand',
    targetId: 'brand-1',
    status: 'success',
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    details: { changedFields: ['name', 'website'] },
  },
  {
    id: 'log-3',
    timestamp: new Date('2024-04-18T16:45:00Z'),
    actor: 'john@example.com',
    action: 'suspend',
    module: 'organizations',
    targetEntity: 'Brand',
    targetId: 'brand-4',
    status: 'success',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    details: { reason: 'Payment overdue' },
  },
  {
    id: 'log-4',
    timestamp: new Date('2024-04-18T09:20:00Z'),
    actor: 'sarah@example.com',
    action: 'change_plan',
    module: 'subscriptions',
    targetEntity: 'Subscription',
    targetId: 'sub-2',
    status: 'success',
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    details: { oldPlan: 'starter', newPlan: 'professional' },
  },
];
